package com.project.bibly_be.sermon.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ContentDTO {
    private Long contentId;       // Auto-generated by the database
    private String fileCode;      // Unique identifier for the content
    private String contentText;   // Actual content text
}
